project:
  type: website

website:
  title: "Anshuman's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/avas0027
      - text: Posts
        href: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css



